### PR TITLE
feat(connection): Add adfs_server option

### PR DESCRIPTION
**Pull request by Larrymagic13**
This adds the adfs_server option for Auth0 connections.

### CODE REVIEW

**Comment by Larrymagic13** [comment]
@alexkappa this set of checks seem to fail related to the ssl keys that are being sent. It seems this is happening on the last 3 PR's. This builds locally fine and I am able to use the new provider to add an ADFS Server connection to Auth0. Is there something we are missing, or does something else need to be updated for this merge and build to pass?

**Comment by alexkappa** [comment]
You’re right it was a change related to the gogetcookies.sh being encrypted as per googles recommendation. I think I’ll have to revert it, sorry about that

**Comment by Larrymagic13** [comment]
@alexkappa what is the typical release schedule for this repository? I ask because our build pipeline uses the following command to pull this and then run our terraform based on this.

curl -OL https://github.com/yieldr/terraform-provider-auth0/releases/download/v0.1.14/terraform-provider-auth0_v0.1.14_linux_amd64.tar.gz

Obviously, we would update with the latest version, but we do need the code that was just merged. Thanks for your help!

**Comment by alexkappa** [comment]
Normally I would release a new version when something is merged. I must have forgot to do that last night, I’ll push a new release tonight

**Comment by Larrymagic13** [comment]
Awesome, thanks!

**Comment by alexkappa** [comment]
Just released 0.1.19 @Larrymagic13, thanks for helping out :)

**Pull request merged**
