### PR TITLE
Upgrade go-auth0/auth0 from v4 -> v5

### PR DESCRIPTION
**Pull request by kpurdon**
### Proposed Changes

* Upgrades the `go-auth0/auth0` package to v5 unlocking new features (log streams, fixed saml connection, ...)

#### Acceptance Test Output

```
==> Checking that code complies with gofmt requirements...
?   	github.com/alexkappa/terraform-provider-auth0	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_debugDefaults
--- PASS: TestProvider_debugDefaults (0.00s)
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (25.54s)
=== RUN   TestAccClient
--- PASS: TestAccClient (1.55s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (10.02s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (3.02s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (2.56s)
=== RUN   TestAccConnection
--- PASS: TestAccConnection (9.14s)
=== RUN   TestAccConnectionAD
--- PASS: TestAccConnectionAD (1.64s)
=== RUN   TestAccConnectionAzureAD
--- PASS: TestAccConnectionAzureAD (2.29s)
=== RUN   TestAccConnectionOIDC
--- PASS: TestAccConnectionOIDC (2.46s)
=== RUN   TestAccConnectionOAuth2
--- PASS: TestAccConnectionOAuth2 (8.77s)
=== RUN   TestAccConnectionWithEnbledClients
--- PASS: TestAccConnectionWithEnbledClients (14.79s)
=== RUN   TestAccConnectionSMS
--- PASS: TestAccConnectionSMS (1.73s)
=== RUN   TestAccConnectionEmail
--- PASS: TestAccConnectionEmail (2.94s)
=== RUN   TestAccConnectionSalesforce
--- PASS: TestAccConnectionSalesforce (7.58s)
=== RUN   TestAccConnectionGoogleOAuth2
--- PASS: TestAccConnectionGoogleOAuth2 (1.39s)
=== RUN   TestAccConnectionFacebook
--- PASS: TestAccConnectionFacebook (2.50s)
=== RUN   TestAccConnectionApple
--- PASS: TestAccConnectionApple (9.24s)
=== RUN   TestAccConnectionLinkedin
--- PASS: TestAccConnectionLinkedin (3.55s)
=== RUN   TestAccConnectionGitHub
--- PASS: TestAccConnectionGitHub (1.76s)
=== RUN   TestAccConnectionConfiguration
--- PASS: TestAccConnectionConfiguration (2.64s)
=== RUN   TestConnectionInstanceStateUpgradeV0
=== RUN   TestConnectionInstanceStateUpgradeV0/Empty
=== RUN   TestConnectionInstanceStateUpgradeV0/Zero
=== RUN   TestConnectionInstanceStateUpgradeV0/NonZero
=== RUN   TestConnectionInstanceStateUpgradeV0/Invalid
--- PASS: TestConnectionInstanceStateUpgradeV0 (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Empty (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Zero (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/NonZero (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Invalid (0.00s)
=== RUN   TestAccConnectionSAML
--- PASS: TestAccConnectionSAML (8.85s)
=== RUN   TestAccCustomDomain
--- PASS: TestAccCustomDomain (1.41s)
=== RUN   TestAccEmailTemplate
--- PASS: TestAccEmailTemplate (7.88s)
=== RUN   TestAccEmail
--- PASS: TestAccEmail (9.89s)
=== RUN   TestAccGlobalClient
--- PASS: TestAccGlobalClient (3.38s)
=== RUN   TestAccHook
--- PASS: TestAccHook (7.93s)
=== RUN   TestHookNameRegexp
--- PASS: TestHookNameRegexp (0.00s)
=== RUN   TestAccPrompt
--- PASS: TestAccPrompt (1.87s)
=== RUN   TestAccResourceServer
--- PASS: TestAccResourceServer (8.37s)
=== RUN   TestAccRole
--- PASS: TestAccRole (10.98s)
=== RUN   TestAccRolePermissions
--- PASS: TestAccRolePermissions (9.88s)
=== RUN   TestAccRuleConfig
--- PASS: TestAccRuleConfig (9.54s)
=== RUN   TestAccRule
--- PASS: TestAccRule (1.27s)
=== RUN   TestRuleNameRegexp
--- PASS: TestRuleNameRegexp (0.00s)
=== RUN   TestAccTenant
--- PASS: TestAccTenant (8.37s)
=== RUN   TestAccUserMissingRequiredParams
--- PASS: TestAccUserMissingRequiredParams (0.01s)
=== RUN   TestAccUser
--- PASS: TestAccUser (25.11s)
=== RUN   TestAccUserIssue218
--- PASS: TestAccUserIssue218 (2.55s)
=== RUN   TestAccUserChangeUsername
--- PASS: TestAccUserChangeUsername (16.06s)
=== RUN   TestMapData
=== RUN   TestMapData/GetOk
=== RUN   TestMapData/GetOkExists
--- PASS: TestMapData (0.00s)
    --- PASS: TestMapData/GetOk (0.00s)
    --- PASS: TestMapData/GetOkExists (0.00s)
=== RUN   TestJSON
--- PASS: TestJSON (0.00s)
=== RUN   TestIsNil
--- PASS: TestIsNil (0.00s)
PASS
coverage: 79.7% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	248.901s	coverage: 79.7% of statements
?   	github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug	[no test files]
=== RUN   TestString
--- PASS: TestString (0.00s)
=== RUN   TestTemplate
--- PASS: TestTemplate (0.00s)
PASS
coverage: 75.0% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/random	0.350s	coverage: 75.0% of statements
=== RUN   TestIsURLWithNoFragment
--- PASS: TestIsURLWithNoFragment (0.00s)
PASS
coverage: 52.9% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation	0.099s	coverage: 52.9% of statements
?   	github.com/alexkappa/terraform-provider-auth0/version	[no test files]
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Review by alexkappa — APPROVED** [review]
@kpurdon the changes look good! Thanks for helping out.

Only thing, we might need a migration for the int -> float type change. Shouldn't be a tough one, but I can use one from another resource.

Otherwise, I will test the changes and merge this in.

**Comment by kpurdon** [comment]
@alexkappa thanks! If you can point me at a migration example I'd be happy to add it.

**Comment by gagalago** [comment]
I suppose that @alexkappa want that you perform a state migration like we can see them in the official documentation https://www.terraform.io/docs/extend/resources/state-migration.html

**Review by alexkappa — APPROVED** [review]

**Comment by alexkappa** [comment]
Indeed I was referring to a state migration. Luckily it didn't seem necessary as the tests would have exposed such a need.

**Pull request merged**
