### PR TITLE
Implements the native_social_login stanza on the Client API.

### PR DESCRIPTION
**Pull request by cthos**
This setting is used to toggle "Enable native Apple/Facebook" login on
and off.

### Proposed Changes

* Adds support for the `native_social_login` stanza in the Client API. 
* Adds documentation
* Updates Mobile Tests

Fixes #0000

#### Acceptance Test Output

Ran the whole suite, but only included the relevant part:

```
$ make testacc TESTS=TestAccClient          
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (22.16s)
=== RUN   TestAccClient
--- PASS: TestAccClient (2.16s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (11.15s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (3.07s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.02s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.59s)
=== RUN   TestAccClientMobile
--- PASS: TestAccClientMobile (10.77s)
=== RUN   TestAccClientMobileValidationError
--- PASS: TestAccClientMobileValidationError (0.02s)
PASS
coverage: 21.7% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     53.407s coverage: 21.7% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Review by kiranms-newpage — APPROVED** [review]
LGTM

**Comment by ca-simone-chiorazzo** [comment]
@kiranms-newpage Any chance to get this PR merged? It would solve also the issue that I've opened yesterday https://github.com/alexkappa/terraform-provider-auth0/issues/488

**Comment by kiranms-newpage** [comment]
@ca-simone-chiorazzo sorry, I don't have permission to merge. We also needed this functionality along with few other. But none of them are being merged :-(

**Comment by lorthirk** [comment]
+1!

**Comment by krissetto** [comment]
This would be needed on my side too, I hope we can get this merged asap!

**Comment by ca-simone-chiorazzo** [comment]
@sergiughf It is something that you can handle on behalf of @alexkappa?

**Comment by sergiughf** [comment]
Hey folks, I'll take a look ASAP.

**Comment by sergiughf** [comment]
I added a few improvements in https://github.com/alexkappa/terraform-provider-auth0/pull/453#:~:text=issues%20in%20pr-,a965541,-Add%20CHANGELOG and released this under https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.25.1
! 🥳 

Thank you so much for the contribution @cthos! It was a really great PR to review! 

And really appreciate everyone's patience, @ca-simone-chiorazzo, @krissetto, @lorthirk, @kiranms-newpage.

**Comment by kiranms-newpage** [comment]
Thanks a lot @sergiughf .

**Comment by ca-simone-chiorazzo** [comment]
Thanks, @sergiughf !

**Comment by cthos** [comment]
> Thank you so much for the contribution @cthos! It was a really great PR to review!

Aw, thanks! And thanks to you as well @sergiughf

**Pull request merged**
