### PR TITLE
add additional refresh token config options

### LINKED ISSUE #311: Add support for additional client refresh_token configurations
### Description

These api fields for client refresh_token are not currently supported:
```
infinite_token_lifetime
idle_token_lifetime
infinite_idle_token_lifetime
```

### New or Affected Resource(s)

* auth0_client

### Potential Terraform Configuration

```hcl
resource "auth0_client" "default" {
...
  refresh_token {
    idle_token_lifetime              = 2592000
    infinite_idle_token_lifetime = true
    infinite_token_lifetime        = true
  }
}

```

### References

* https://github.com/go-auth0/auth0/issues/183

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by woz5999**
### Proposed Changes

* add support for client refresh_token fields 
```
idle_token_lifetime
infinite_idle_token_lifetime
infinite_token_lifetime 
```

Fixes #311 
Fixes #307

#### Acceptance Test Output

```
$ make testacc TESTS=TestAccClient    
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (25.72s)
=== RUN   TestAccClient
--- PASS: TestAccClient (2.79s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (5.65s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (4.21s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.81s)
=== RUN   TestAccClientMobile
--- PASS: TestAccClientMobile (4.05s)
=== RUN   TestAccClientMobileValidationError
--- PASS: TestAccClientMobileValidationError (0.02s)
PASS
coverage: 24.4% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     46.570s coverage: 24.4% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.296s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.293s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
```

Note that the acceptance tests were run pointing to an updated sdk with the changes here: https://github.com/go-auth0/auth0/issues/183

This is a draft until those get merged and released upstream.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by yvovandoorn** [comment]
@woz5999 I see this is marked as draft, is it ready for review?

**Comment by woz5999** [comment]
@yvovandoorn it's dependent on go-auth0/auth0#183
i also need to do a bit more testing/debugging today.

**Comment by woz5999** [comment]
update acceptance test outputs after fixes and updating tests:

```
make testacc TESTS=TestAccClient                  
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (23.92s)
=== RUN   TestAccClient
--- PASS: TestAccClient (2.10s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (6.12s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (9.80s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.44s)
=== RUN   TestAccClientMobile
--- PASS: TestAccClientMobile (3.12s)
=== RUN   TestAccClientMobileValidationError
--- PASS: TestAccClientMobileValidationError (0.01s)
PASS
coverage: 24.6% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     48.847s coverage: 24.6% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.289s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.185s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
```

**Comment by woz5999** [comment]
@yvovandoorn this is ready for review now

**Review by alexkappa — APPROVED** [review]

**Comment by woz5999** [comment]
@alexkappa  rebased and looks like the label check is still due to a missing repo-token now?

**Pull request merged**
