### PR TITLE
Add set_user_root_attributes to SAML connection options

### LINKED ISSUE #284: set_user_root_attributes missing for samlp auth0_connection
### Description

From the management API docs for auth0_connection:

>  options.set_user_root_attributes can be set only for enterprise connections, social connections or custom database connections (using external users store)

> Determines whether the 'name', 'given_name', 'family_name', 'nickname', and 'picture' attributes can be independently updated when using an external IdP. Possible values are 'on_each_login' (default value, it configures the connection to automatically update the root attributes from the external IdP with each user login. When this setting is used, root attributes cannot be independently updated), 'on_first_login' (configures the connection to only set the root attributes on first login, allowing them to be independently updated thereafter)

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/alexkappa/auth0 v0.15.2
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "samlp" {
  for_each = var.saml_connections

  name         = each.key
  display_name = each.value.display_name
  strategy     = "samlp"
  enabled_clients = [
   ...
  ]
  options {
    signing_cert     = each.value.cert
    sign_in_endpoint = each.value.sign_in_endpoint
    tenant_domain    = each.value.domain
    // TODO set_user_root_attributes = "on_first_login"
    domain_aliases = [each.value.domain]
  }
  realms = [each.key]
}
```

### Expected Behavior

Should be able to use `set_user_root_attributes`

### Actual Behavior

Cannot set the value and the default ends up getting set overriding any existing setting.

### Steps to Reproduce

1. `terraform apply`

### References

* https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by kpurdon**
### Proposed Changes

* Adds the missing `set_user_root_attributes` option to the SAML connection type

~Currently rebased on https://github.com/alexkappa/terraform-provider-auth0/pull/291, will rebase once that is merged.~ done

Fixes #284 Replaces #285 (building on v5 of go-auth0)

#### Acceptance Test Output

```
==> Checking that code complies with gofmt requirements...
?   	github.com/alexkappa/terraform-provider-auth0	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_debugDefaults
--- PASS: TestProvider_debugDefaults (0.00s)
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (26.26s)
=== RUN   TestAccClient
--- PASS: TestAccClient (1.66s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (3.94s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (8.92s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (2.64s)
=== RUN   TestAccConnection
--- PASS: TestAccConnection (8.64s)
=== RUN   TestAccConnectionAD
--- PASS: TestAccConnectionAD (1.50s)
=== RUN   TestAccConnectionAzureAD
--- PASS: TestAccConnectionAzureAD (2.19s)
=== RUN   TestAccConnectionOIDC
--- PASS: TestAccConnectionOIDC (2.70s)
=== RUN   TestAccConnectionOAuth2
--- PASS: TestAccConnectionOAuth2 (8.63s)
=== RUN   TestAccConnectionWithEnbledClients
--- PASS: TestAccConnectionWithEnbledClients (15.05s)
=== RUN   TestAccConnectionSMS
--- PASS: TestAccConnectionSMS (1.56s)
=== RUN   TestAccConnectionEmail
--- PASS: TestAccConnectionEmail (2.41s)
=== RUN   TestAccConnectionSalesforce
--- PASS: TestAccConnectionSalesforce (7.62s)
=== RUN   TestAccConnectionGoogleOAuth2
--- PASS: TestAccConnectionGoogleOAuth2 (1.64s)
=== RUN   TestAccConnectionFacebook
--- PASS: TestAccConnectionFacebook (2.19s)
=== RUN   TestAccConnectionApple
--- PASS: TestAccConnectionApple (8.64s)
=== RUN   TestAccConnectionLinkedin
--- PASS: TestAccConnectionLinkedin (2.42s)
=== RUN   TestAccConnectionGitHub
--- PASS: TestAccConnectionGitHub (1.69s)
=== RUN   TestAccConnectionConfiguration
--- PASS: TestAccConnectionConfiguration (8.79s)
=== RUN   TestConnectionInstanceStateUpgradeV0
=== RUN   TestConnectionInstanceStateUpgradeV0/Empty
=== RUN   TestConnectionInstanceStateUpgradeV0/Zero
=== RUN   TestConnectionInstanceStateUpgradeV0/NonZero
=== RUN   TestConnectionInstanceStateUpgradeV0/Invalid
--- PASS: TestConnectionInstanceStateUpgradeV0 (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Empty (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Zero (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/NonZero (0.00s)
    --- PASS: TestConnectionInstanceStateUpgradeV0/Invalid (0.00s)
=== RUN   TestAccConnectionSAML
--- PASS: TestAccConnectionSAML (2.32s)
=== RUN   TestAccCustomDomain
--- PASS: TestAccCustomDomain (7.53s)
=== RUN   TestAccEmailTemplate
--- PASS: TestAccEmailTemplate (2.34s)
=== RUN   TestAccEmail
--- PASS: TestAccEmail (9.46s)
=== RUN   TestAccGlobalClient
--- PASS: TestAccGlobalClient (9.45s)
=== RUN   TestAccHook
--- PASS: TestAccHook (2.82s)
=== RUN   TestHookNameRegexp
--- PASS: TestHookNameRegexp (0.00s)
=== RUN   TestAccPrompt
--- PASS: TestAccPrompt (2.01s)
=== RUN   TestAccResourceServer
--- PASS: TestAccResourceServer (8.53s)
=== RUN   TestAccRole
--- PASS: TestAccRole (16.82s)
=== RUN   TestAccRolePermissions
--- PASS: TestAccRolePermissions (10.09s)
=== RUN   TestAccRuleConfig
--- PASS: TestAccRuleConfig (3.33s)
=== RUN   TestAccRule
--- PASS: TestAccRule (7.46s)
=== RUN   TestRuleNameRegexp
--- PASS: TestRuleNameRegexp (0.00s)
=== RUN   TestAccTenant
--- PASS: TestAccTenant (2.23s)
=== RUN   TestAccUserMissingRequiredParams
--- PASS: TestAccUserMissingRequiredParams (0.03s)
=== RUN   TestAccUser
--- PASS: TestAccUser (25.73s)
=== RUN   TestAccUserIssue218
--- PASS: TestAccUserIssue218 (9.01s)
=== RUN   TestAccUserChangeUsername
--- PASS: TestAccUserChangeUsername (9.96s)
=== RUN   TestMapData
=== RUN   TestMapData/GetOk
=== RUN   TestMapData/GetOkExists
--- PASS: TestMapData (0.00s)
    --- PASS: TestMapData/GetOk (0.00s)
    --- PASS: TestMapData/GetOkExists (0.00s)
=== RUN   TestJSON
--- PASS: TestJSON (0.00s)
=== RUN   TestIsNil
--- PASS: TestIsNil (0.00s)
PASS
coverage: 79.7% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	248.618s	coverage: 79.7% of statements
?   	github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug	[no test files]
=== RUN   TestString
--- PASS: TestString (0.00s)
=== RUN   TestTemplate
--- PASS: TestTemplate (0.00s)
PASS
coverage: 75.0% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/random	0.319s	coverage: 75.0% of statements
=== RUN   TestIsURLWithNoFragment
--- PASS: TestIsURLWithNoFragment (0.00s)
PASS
coverage: 52.9% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation	0.298s	coverage: 52.9% of statements
?   	github.com/alexkappa/terraform-provider-auth0/version	[no test files]
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by alexkappa** [comment]
@kpurdon could you please rebase your branch to take the v5 changes in effect?

**Comment by kpurdon** [comment]
@alexkappa rebased and re-ran tests succesfully.

**Comment by kpurdon** [comment]
@alexkappa this should be ready to go, please let me know if you'd like any additional work done here. Thanks!

**Review by alexkappa — APPROVED** [review]

**Comment by alexkappa** [comment]
Merging this in, thanks @kpurdon!

**Pull request merged**
