### PR TITLE
Fix send-phone-message hook

### PR DESCRIPTION
**Pull request by ninja-**
### Proposed Changes

* Fix send-phone-message hook

#### Acceptance Test Output

```
$ make testacc TESTS=TestAccXXX

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by alexkappa** [comment]
Thank you for submitting a fix @ninja- . Cheers!

**Comment by ninja-** [comment]
Thanks, it's a major blocker for a project I am working on :P any ETA on when this will be live in terraform plugins?

**Comment by alexkappa** [comment]
I see it is already released. Version 0.10.3.

**Comment by ninja-** [comment]
Error: provider.auth0: no suitable version installed
  version requirements: "0.10.3"
  versions installed: "0.10.2"

:(

**Comment by ninja-** [comment]
ah nevermind, I needed to remove `.terraform`. Using `terraform init` was not enough.

**Comment by alexkappa** [comment]
Strange. I can see the hashicorp team release job was successful and a new
version appeared here:
https://releases.hashicorp.com/terraform-provider-auth0/

Perhaps give it some time and try again a little later?

**Pull request merged**
