### PR TITLE
add auth0_client and auth0_global_client data sources and tests

### LINKED ISSUE #279: Support Terraform data sources
### Description

Aside Terraform resources, there is also another [data source](https://www.terraform.io/docs/configuration/data-sources.html) type which is roughly the readonly version of a resource.  

That would be a great enhancement to this provider to include data source support. Since I have already worked on a terraform provider I am happy to submit a PR for it.
 
### New or Affected Resource(s)

Ideally all the existing resources would have their data source counterpart.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by yinzara**
### Proposed Changes

* Add "auth0_client" data source
* Add "auth0_global_client" data source

Fixes #279 

#### Acceptance Test Output

```
$ make testacc TESTS=TestAccData
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccDataClientByName
--- PASS: TestAccDataClientByName (3.94s)
=== RUN   TestAccDataClientById
--- PASS: TestAccDataClientById (9.42s)
=== RUN   TestAccDataGlobalClient
--- PASS: TestAccDataGlobalClient (2.92s)
PASS
coverage: 20.6% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     16.549s coverage: 20.6% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.233s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.367s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by yvovandoorn** [comment]
Hi @yinzara! Thank you for this contribution. 

I think the PR looks good, but do you mind changing it from `data_<resource>` to `data_source_<resource>`, to match (for example) the AWS provider (e.g. https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_acm_certificate.go).

**Comment by yinzara** [comment]
Absolutely, I'll submit an update as soon as I'm available.

**Comment by yvovandoorn** [comment]
*One* more thing that is missing is if you can add a bit of docs about this data source!

Another PR, #281, has a bit of documentation (https://github.com/alexkappa/terraform-provider-auth0/blob/7f443aca26b23b7bf5d89d71799679ffc00bf7c2/docs/datasources/user.md). Would be great to get that here as well so that the two PRs that start providing data sources have supporting documentation. 

Thanks again @yinzara  for your contribution!

**Review by alexkappa — APPROVED** [review]
Looks good to me, thanks @yinzara!

The only thing I would suggest is to follow some of the practices found in other providers around sharing schemas between resources and data sources. Many providers re-define the entire schema for data sources which I find repetitive and tedious. Others, however, like the google-beta provider may have some practices we can borrow.

For example: 
- https://github.com/hashicorp/terraform-provider-google-beta/blob/217cf8662e9b25ed0cb7622e27adc0fd364dcc3d/google-beta/datasource_helpers.go#L13
- https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/data_source_cloud_run_service.go

**Comment by yinzara** [comment]
Funny you mention that, I actually created `makeComputed` for this purpose, but `datasourceSchemaFromResourceSchema` is even better so I just copied it exactly from google.

Since their project is also Mozilla v2 licensed, there is no reason we can't do that as don't even need to include the license.


I've also added the docs requested and missing docs for the auth0_global_client and auth0_log_stream resources and the new "secrets" attributes of hooks.


Here is the result of rerunning the acceptance tests:
```
make testacc TESTS=TestAccData
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccDataClientByName
--- PASS: TestAccDataClientByName (3.95s)
=== RUN   TestAccDataClientById
--- PASS: TestAccDataClientById (9.49s)
=== RUN   TestAccDataGlobalClient
--- PASS: TestAccDataGlobalClient (2.95s)
PASS
coverage: 20.6% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     16.655s coverage: 20.6% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.226s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.147s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
```

**Comment by yvovandoorn** [comment]
Hi @yinzara, unfortunately, while passing locally for me in testing at first. Upon merge, it is epicly failing on expecting custom_login_page_on being a different value. I quickly took a look at the test and I think its missing an include string in the test. 

For now I've reverted it.

**Comment by yvovandoorn** [comment]
Hi @yinzara do you mind submitting the updated test to re-open this PR (or submit a new one?)

Thanks!

**Pull request merged**
