### PR TITLE
[WIP] add new resource auth0_branding

### PR DESCRIPTION
**Pull request by apricote**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Related to #124

Changes proposed in this pull request:

* Add new resource `auth0_branding`

Output from acceptance testing:

```
$ make testacc TESTS=TestAccBranding
==> Checking that code complies with gofmt requirements...
?       github.com/terraform-providers/terraform-provider-auth0 [no test files]
=== RUN   TestAccBranding
--- PASS: TestAccBranding (1.89s)
PASS
coverage: 8.9% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0   1.902s  coverage: 8.9% of statements
?       github.com/terraform-providers/terraform-provider-auth0/auth0/internal/debug    [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0/internal/random   0.006s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0/internal/validation       0.002s  coverage: 0.0% of statements [no tests to run]
```

### CODE REVIEW

**Comment by alexkappa** [comment]
Looking very good so far @apricote ;)

As far as I can tell, you are only missing some tests, right? Otherwise the direction you took is a good one and aligned with the rest of the project.

**Comment by apricote** [comment]
Thanks @alexkappa , I used `auth0_tenant` as the orientation for this.

I added the tests and documentation.

Now there is only one small bug left: The `font` attribute is required and causes a `400 Bad Request` if not set, I will get around to this later this week.

About the `github.com/go-auth0/auth0` update, should I create a new PR or include it here or do you want to do that?

**Comment by alexkappa** [comment]
> About the github.com/go-auth0/auth0 update, should I create a new PR or include it here or do you want to do that?

If you rebase or merge the latest changes from master you'll see the go-auth0 package is in version v4.3.1. That should do it right?

**Comment by apricote** [comment]
> If you rebase or merge the latest changes from master you'll see the go-auth0 package is in version v4.3.1. That should do it right?

Yes! Just rebased and pushed it.

**Comment by apricote** [comment]
I fixed the bug where it would return `400 Bad Request` if no `font` attribute is set. PR is now ready for review

**Comment by alexkappa** [comment]
@apricote is this ready for a final review?

**Comment by novascreen** [comment]
@apricote it would be awesome to get this over the finish line, what's missing to get this ready for review?

**Comment by relu** [comment]
@alexkappa, @apricote anything I can do to help move this through? I can offer to take care of the rest of the work if need be, we really need this feature!

**Comment by apricote** [comment]
As far as I can remember this was considered finished and awaiting review by me, see [this comment](https://github.com/alexkappa/terraform-provider-auth0/pull/199#issuecomment-624817184).

At some point the official documentation from Auth0 about this feature disappeared and I was unsure if they will remove this API but everything is back now.

**Pull request closed without merging**
