### PR TITLE
should_trust_email_verified_connection added to Azure AD connection

### PR DESCRIPTION
**Pull request by mafodev**
I need some help on this one - please see the comment below.

### Proposed Changes

* WIP Added should_trust_email_verified_connection for Azure AD connections

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by mafodev** [comment]
I have been trying to add the should_trust_email_verified_connection option to the connections. When trying to test the changes by changing the connection option via terraform plan and apply the new setting is not applied in my auth0 connection.

The output of the terraform plan command shows the expected change but on running the apply the setting is not actually changed. Does anyone have an idea on this? Maybe @ollystephens has an idea? - he mentioned on this commit on go-auth0
that he has the changes for this one ready to go

**Comment by yvovandoorn** [comment]
I think what it is missing is the necessary test case in `auth0/resource_auth0_connection_test.go` that takes into consideration the property addition. 

Try getting that to work and then posting a **PASS** for `make testacc TESTS=TestAccConnectionAzureAD`

**Comment by mafodev** [comment]
Hi @yvovandoorn, thanks for your reply. 
I am not sure if I understand you correctly here. I extended the existing test case for the Azure AD connection to take the "should_trust_email_verified_connection"-option into account. The test passes if I execute the command you provided:

test

However if I try to apply a terraform connection template the changes is not applied (looking at it via the Auth0 Dashboard).

The relevant section from the template:
````
resource "auth0_connection" "connection_waad" {
  name     = "connectionname-waad"
  strategy = "waad"
  enabled_clients = [
    for application in var.waad_enabled : auth0_client.spa_applications[tostring(application)].client_id
  ]
  is_domain_connection = false
  options {
    tenant_domain = "somedomain.com"
    domain        = "somedomain.onmicrosoft.com"
    domain_aliases = [
      "somethingsomething.onmicrosoft.com",
      "something.de"
    ]
    scopes                                 = ["ext_groups"]
    use_wsfed                              = false
    client_id                              = "11111111-1111-1111-1111-111111111111"
    client_secret                          = "77777777-7777-7777-7777-777777777777"
    waad_protocol                          = "openid-connect"
    max_groups_to_retrieve                 = 25
    api_enable_users                       = true
    waad_common_endpoint                   = false
    should_trust_email_verified_connection = "always_set_emails_as_verified"
  }
}
````

The settings section in the Auth0 dashboard after running terraform apply:



I can not seem to figure this one out. Any ideas on why the change is not applied correctly?

**Comment by mafodev** [comment]
Closing this because after accidentally pushing the build provider fiel this turned into chaos. Will open a new PR for this - Sorry

**Pull request closed without merging**
