### PR TITLE
Only send tenant setting flags if values changed

### LINKED ISSUE #160: Can't set disable_clickjack_protection_headers = false
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.19
`terraform-provider-auth0` at f3bab1e

### Affected Resource(s)

* `auth0_tenant`

### Terraform Configuration Files

```hcl
resource "auth0_tenant" "default" {
  flags {
    disable_clickjack_protection_headers = false
  }
}
```

### Expected Behavior

* `disable_clickjack_protection_headers` gets set to `false`

### Actual Behavior

* Terraform's plan says it'll set `disable_clickjack_protection_headers = false` every time
* If I [check the clickjacking protection settings](https://auth0.com/docs/migrations/guides/clickjacking-protection), “Disable clickjacking protection for Classic Universal Login” is still enabled
* Auth0's logs show a `sapi` with description “Update tenant settings”, in which `details.request.body.flags` sets `enable_custom_domain_in_emails = true` and `enable_public_signup_user_exists_error = true` despite the plan not needing either to change, and _doesn't_ contain `disable_clickjack_protection_headers = false`
* `terraform state pull` shows the flags in the state as:

```json
{
  "change_pwd_flow_v1": false,
  "disable_clickjack_protection_headers": true,
  "enable_apis_section": false,
  "enable_client_connections": false,
  "enable_custom_domain_in_emails": true,
  "enable_dynamic_client_registration": false,
  "enable_legacy_logs_search_v2": false,
  "enable_pipeline2": false,
  "enable_public_signup_user_exists_error": true,
  "universal_login": false
}
```

I note the `enable_custom_domain_in_emails` and `enable_public_signup_user_exists_error` flags you're telling Auth0 to set aren't present in the state.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None of which I'm aware.

### References

None of which I'm aware.

### PR DESCRIPTION
**Pull request by emilhdiaz**
### Proposed Changes

This modification makes it such that tenant setting flags will only be included in the `PATCH /api/v2/tenants/settings` call if they have changed. This proposed change addresses use cases for Auth0 private cloud and enterprise customers whose tenants do not allow updates of certain tenant settings flags. Even the mere presence of these flags in the API call, irrespective of the values changing or not, will cause the API to return an error response. With these proposed changes, the tenant setting flags will simply be omitted from the API call if unchanged, thus bypassing the issue altogether. 

NOTE: For other Auth0 public cloud customers, the previous behavior will continue to function as it previously did. In other words, this change is backwards compatible. 

Fixes #160

#### Acceptance Test Output

The following acceptance test was conducted against an Auth0 public cloud enterprise tenant. These specific code changes have been verified against an Auth0 private cloud enterprise tenant. 

```
$ make testacc TESTS=TestAccXXX
==> Checking that code complies with gofmt requirements...
?   	github.com/alexkappa/terraform-provider-auth0	[no test files]
=== RUN   TestAccClientGrant
--- PASS: TestAccClientGrant (24.28s)
=== RUN   TestAccClient
--- PASS: TestAccClient (1.36s)
=== RUN   TestAccClientZeroValueCheck
--- PASS: TestAccClientZeroValueCheck (9.35s)
=== RUN   TestAccClientRotateSecret
--- PASS: TestAccClientRotateSecret (8.39s)
=== RUN   TestAccClientInitiateLoginUri
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (2.16s)
=== RUN   TestAccClientMobile
--- PASS: TestAccClientMobile (8.43s)
=== RUN   TestAccClientMobileValidationError
--- PASS: TestAccClientMobileValidationError (0.02s)
PASS
coverage: 24.5% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	54.363s	coverage: 24.5% of statements
?   	github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug	[no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/random	0.249s	coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation	0.107s	coverage: 0.0% of statements [no tests to run]
?   	github.com/alexkappa/terraform-provider-auth0/version	[no test files]
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by yvovandoorn** [comment]
This is a really good change @emilhdiaz. There are often Auth0 customers who could have unique tenant flags enabled, whether it's evaluating new features, specific protection capabilities are enabled, etc. 

@alexkappa could you review this one as it is a behavioral change (even if it is backwards compatible) that changes the way the provider applies changes. This change opens up the fact that the state over a tenant is co-managed server/Auth0 side.

**Comment by alexkappa** [comment]
@emilhdiaz @yvovandoorn this issue has been troubling us for a really long time. Originally the provider would only send fields if they have changed, which was causing several issues (#185, #197). The fix came with PR #194. Issue #185 is particularly interesting as it has all the backstory, as well as issues that will resurface if this PR gets merged.

Perhaps if we are more selective in using the `IsNewResource()` and `HasChange()` conditions we can maintain the fixes that #194 brought, and solving the issue you are facing as well.

Which flags in particular, when set, give you errors?

**Comment by yvovandoorn** [comment]
> Which flags in particular, when set, give you errors?

I can't speak to @emilhdiaz specific issues but as someone at Auth0, the tenant flags portion of a tenant is one of the areas of configuration that could differ configuration-wise versus the state held by Terraform. 

- New features often get released behind feature flags that are stored as values in the tenant flags (for example new dashboard experience)
- Deprecated features often get "turned off" behind flags in the tenant flags (for example impersonation)
- Support has the ability to enable/disable certain functionality hidden behind flags based on the usage patterns in a tenant. 

The flags aren't specific as they are ever-changing as the product evolves. Some are well defined. Some are flags only to be used in certain situations.

**Comment by alexkappa** [comment]
Hi @emilhdiaz, what you are suggesting makes sense, but the mechanism that determines whether a value has explicitly been  defined is from the terraform SDKs [ResourceData.GetOk](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema#ResourceData.GetOk) / [ResourceData.GetOkExists](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema#ResourceData.GetOkExists) methods. The latter is a special case for booleans. By the SDK documentation, this should already be the expected behavior but I'm afraid it doesn't work that way in practice for reasons I can't quite understand.

In #241 I've made another attempt in this direction, but as you can see I [kept boolean fields](https://github.com/alexkappa/terraform-provider-auth0/pull/241/files#diff-0c0f8d67c6562c0f514c1d9ae3813f4724d6890157b3c08e557af4a3eefc8950R201-R207) as it was breaking in unexpected ways.

If you are feeling adventurous, try to see if [Bool](https://github.com/alexkappa/terraform-provider-auth0/blob/8d4eb6cbf98f895eaa6d959098bf2c371f8275bc/auth0/resource_data.go#L241-L247) can be switched to using `GetOk` instead of `GetOkExists`.

If that doesn't get us where we want to be, we could perhaps consider sending fields that are safe to send, and all others conditionally (i.e. `IsNewResource`, `HasChange`)?

**Comment by emilhdiaz** [comment]
@alexkappa I've been spending some time tinkering with a couple options as well, and I think I'm starting to gain a better appreciation for the complexity of the problem 😄  !

It appears irrespective of what flags are present when state is read from the API and flattened into the `ResourceData` object via the `flattenTenantFlags()` method, terraform will use the schema defined in `resource_auth0_tenant.go` to construct the full `ResourceData`. So flags that are not returned by the API will simply be defaulted to `false` when terraform constructs the local state. After those values are in the local state they are passed through to the create and update methods without any distinction from the other flags that were indeed returned by the API. 

Like you described, it also appears there is no way to know whether a value has explicitly been defined by the user.... at least, not that I know of. 

So then that leaves us with your last suggestion of always sending all safe fields and make the problematic ones conditional. 

Another option, though it's a much bigger change, is to expose a new provider configuration option that allows a user to define "blacklisted" fields from the schema. We would then have to make schema definitions dynamic OR check the blacklist before constructing Auth0 update calls. Thoughts?

**Comment by emilhdiaz** [comment]
Hey @alexkappa, any luck on your end? What do you think of the recent changes I made here?

**Comment by alexkappa** [comment]
I'm not sure its a good idea to have `flags` sent conditionally. `HasChange` could be true if we remove its last element.

For example, this might pass the condition and send an empty object, causing the issue reported in #185.

```diff
-{"foo":true}
+{}
```

What if certain keys, we can always send while most others we send on condition (`HasChange`, `IsNewResource`)? Problem is, I don't know which are safe to always be sent across public, private cloud or enterprise.

**Comment by willvedd** [comment]
@emilhdiaz Thanks for submitting this, this seems like a great first step in addressing this pain point. However, for the reasons that @yvovandoorn and @alexkappa listed above, I'm realizing that the solution is non-trivial. Our team is still familiarizing ourselves with the project and will need a bit more time to understand the issue and strategize an appropriate solution. One initial thought I'm having is if it is more appropriate to address this from the API-side, either by adhering to more RESTful conventions or something else, rather than this project assuming the responsibility entirely. But again, our team just needs to reevaluate.

This project is currently in the process of being migrated to the Auth0 organization and we're unable to migrate PRs over to the new repo. Combined with this tricky issue, we'll need to close this in favor of #513 where the conversation will continue.

**Comment by emilhdiaz** [comment]
@willvedd Understood! Thanks for the update and the consideration.

**Pull request closed without merging**
