### PR TITLE
fixed wrong property names for tokenURL and authorizationURL

### LINKED ISSUE #271: Bug in Oauth2 Connection Support
https://github.com/go-auth0/auth0/issues/146
### Description

While the request generated by the current implementation of the Oauth2 connection strategy, the token_endpoint and authorization_endpoint are not used by the Oauth2 Social connection.

The correct names are tokenURL and authorizationURL.

### Terraform Version

```
Terraform <TERRAFORM_VERSION>
+ provider.auth0 <TERRAFORM_PROVIDER_VERSION>
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "oauth2" {
	name     = "My OAuth2 Connection"
	strategy = "oauth2"
	is_domain_connection = false
	options {
		client_id     = "1234567"
		client_secret = "1234567"
		token_endpoint         = "https://api.paypal.com/v1/oauth2/token"
		authorization_endpoint = "https://www.paypal.com/signin/authorize"
		scopes = [ "openid", "email" ]
		scripts = {
			fetchUserProfile= "function( { return callback(null) }"
		}
	}
}
```

### Expected Behavior
Should be changed to
```hcl
resource "auth0_connection" "oauth2" {
	name     = "My OAuth2 Connection"
	strategy = "oauth2"
	is_domain_connection = false
	options {
		client_id     = "1234567"
		client_secret = "1234567"
		token_url         = "https://api.paypal.com/v1/oauth2/token"
		authorization_url = "https://www.paypal.com/signin/authorize"
		scopes = [ "openid", "email" ]
		scripts = {
			fetchUserProfile= "function( { return callback(null) }"
		}
	}
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/go-auth0/auth0/issues/146

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mcalster**
### Proposed Changes

* Oauth2 strategy now requires two new properties: token_url and authorization_url
* The previous version used token_endpoint and authorization_endpoint, which was correctly added to the connection object in Auth0, but not used to configure the connection.

Fixes #271 
#### Acceptance Test Output

```
$ make testacc TESTS=TestAccConnectionOAuth2
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccConnectionOAuth2
--- PASS: TestAccConnectionOAuth2 (3.25s)
PASS
coverage: 12.5% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     3.690s  coverage: 12.5% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.265s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.312s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by mcalster** [comment]
@alexkappa do you have possebility to release a new version soon? I'm concerned that the longer we wait the more people will encounter this bug.

**Comment by abulford** [comment]
@mcalster thanks for this, I was glad to see OAuth2 support had been added to the provider but found the property name issue you've fixed here (and in the SDK).

I've tested this change and it works for me, though in order to do that I had to bump the `auth0` module version from `v4.6.0` to `v4.7.0` in `go.mod`, because your SDK fix has been released under that new version.  I also merged the latest master into this branch but I think the only change was to the README.

**Comment by mcalster** [comment]
@abulford thx for keeping an eye on the release of 4.7.0 👍 
I've updated go.mod to use the new version and rebased on master. So now it should be good to go :-)

**Comment by abulford** [comment]
@mcalster nice, thanks!  I'll be giving your log stream stuff a spin soon... :)

**Comment by mcalster** [comment]
@alexkappa  this should be ready now

**Review by mcalster — COMMENTED** [review]
LGTM

**Comment by abulford** [comment]
@alexkappa if you're in "merge mode" atm, what would you think of merging this one...?  I've had this merged locally since my comment 11 days ago and has been working fine for me, though admittedly I've not been making any connection changes in that time frame.

**Comment by mcalster** [comment]
> @alexkappa if you're in "merge mode" atm, what would you think of merging this one...? I've had this merged locally since my comment 11 days ago and has been working fine for me, though admittedly I've not been making any connection changes in that time frame.

I’d like to be able to skip my custom built Provider to ger this feature :-)

**Comment by alexkappa** [comment]
@mcalster I prefer to leave the schema fields as is in order to avoid migrating users over. As long as the SDK sends the right fields to the API we should be fine.

**Comment by abkias** [comment]
@alexkappa I'm not sure I understand. It only works if this is patched. It will be created in Auth0 but it won't work, since I used the wrong property names in the API.

**Comment by abkias** [comment]
> @alexkappa I'm not sure I understand. It only works if this is patched. It will be created in Auth0 but it won't work, since I used the wrong property names in the API.

I misremembered the code I can see. With the SDK fixed it's purely a naming inconsistency.

**Pull request closed without merging**
