### PR TITLE
Add support for connect mfa options

### LINKED ISSUE #310: Add support for MFA options in connection resource
### Description

Add support for MFA options in connection resource.
Support already seems to exist in the SDK: https://github.com/go-auth0/auth0/blob/master/management/connection.go#L170

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "database" {
  ...
  options {
    mfa {
      active                 = true
      return_enroll_settings = true
    }
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by woz5999**
### Proposed Changes

* Support connection mfa options

Fixes #310

#### Acceptance Test Output

```
$ make testacc TESTS=TestAccConnection
==> Checking that code complies with gofmt requirements...
?       github.com/alexkappa/terraform-provider-auth0   [no test files]
=== RUN   TestAccConnection
--- PASS: TestAccConnection (6.12s)
=== RUN   TestAccConnectionAD
--- PASS: TestAccConnectionAD (2.36s)
=== RUN   TestAccConnectionAzureAD
--- PASS: TestAccConnectionAzureAD (3.13s)
=== RUN   TestAccConnectionOIDC
--- PASS: TestAccConnectionOIDC (4.93s)
=== RUN   TestAccConnectionOAuth2
--- PASS: TestAccConnectionOAuth2 (3.76s)
=== RUN   TestAccConnectionWithEnbledClients
--- PASS: TestAccConnectionWithEnbledClients (15.09s)
=== RUN   TestAccConnectionSMS
--- PASS: TestAccConnectionSMS (2.01s)
=== RUN   TestAccConnectionEmail
--- PASS: TestAccConnectionEmail (4.02s)
=== RUN   TestAccConnectionSalesforce
--- PASS: TestAccConnectionSalesforce (2.35s)
=== RUN   TestAccConnectionGoogleOAuth2
--- PASS: TestAccConnectionGoogleOAuth2 (1.96s)
=== RUN   TestAccConnectionFacebook
--- PASS: TestAccConnectionFacebook (4.15s)
=== RUN   TestAccConnectionApple
--- PASS: TestAccConnectionApple (3.56s)
=== RUN   TestAccConnectionLinkedin
--- PASS: TestAccConnectionLinkedin (3.66s)
=== RUN   TestAccConnectionGitHub
--- PASS: TestAccConnectionGitHub (8.46s)
=== RUN   TestAccConnectionConfiguration
--- PASS: TestAccConnectionConfiguration (4.51s)
=== RUN   TestAccConnectionSAML
    TestAccConnectionSAML: testing.go:705: Step 0 error: errors during apply:
        
        Error: 400 Bad Request: The signing certificate is not valid. Please provide a .pem or .cer certificate base64 encoded public key
        
          on /var/folders/ny/xc92y7xs1szbdr9skq_s7b4h0000gq/T/tf-test771952802/main.tf line 2:
          (source code not available)
        
        
--- FAIL: TestAccConnectionSAML (0.46s)
FAIL
coverage: 26.1% of statements
FAIL    github.com/alexkappa/terraform-provider-auth0/auth0     70.813s
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no test files]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random     0.272s  coverage: 0.0% of statements [no tests to run]
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/validation 0.297s  coverage: 0.0% of statements [no tests to run]
?       github.com/alexkappa/terraform-provider-auth0/version   [no test files]
FAIL
make: *** [testacc] Error 1
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by woz5999** [comment]
Note that the failed saml test is unrelated to these code changes and appears to be caused by some test dependencies not present in my environment

**Comment by woz5999** [comment]
I'm not sure the cause of the check failure, but it seems unrelated to the code change? Possible build system or transient network issue.

**Review by alexkappa — COMMENTED** [review]
Hi @woz5999, thanks for putting this together! I see the new fields are defined in the schema but I can't find any expand or flatten operations with it.

We might need to add it [here](https://github.com/alexkappa/terraform-provider-auth0/blob/fd9553cf2fb338940b11fe9630ceb34175a3142c/auth0/structure_auth0_connection.go#L59) and [here](https://github.com/alexkappa/terraform-provider-auth0/blob/fd9553cf2fb338940b11fe9630ceb34175a3142c/auth0/structure_auth0_connection.go#L310)

The certificate errors should go away if you rebase your changes on top of the latest master.

**Comment by woz5999** [comment]
@alexkappa changes pushed. not sure the best way to test. Re-ran the acceptance tests and they passed, but they passed the first time too. 

Also rebased and looks like the label check is still failing =[

**Comment by alexkappa** [comment]
@woz5999, awesome! I've merged the changes and will push a release soon. (Not sure why the PR is not marked as merged)

**Comment by woz5999** [comment]
@alexkappa are you sure this was merged? i don't see the changes in master.

**Pull request closed without merging**
