### PR TITLE
Add the "user_invitation" email template option

### PR DESCRIPTION
**Pull request by jackton1**
### Proposed Changes
Adds the `'user_invitation'` email template option. 

See: https://auth0.com/docs/api/management/v2#!/Email_Templates/get_email_templates_by_templateName

#### Acceptance Test Output

```
$ make testacc TESTS=TestAccXXX

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Review by galkin — APPROVED** [review]
looks good for me

**Review by alexkappa — COMMENTED** [review]
Hi @jackton1, thanks for submitting this PR! Would you mind updating the docs for consistencies sake? Email templates are under `docs/resources/email_template.md`.

**Comment by jackton1** [comment]
> Hi @jackton1, thanks for submitting this PR! Would you mind updating the docs for consistencies sake? Email templates are under `docs/resources/email_template.md`.

Done. Thanks

**Comment by jackton1** [comment]
@alexkappa Any chance we could get this through currently blocked by this ??

**Review by alexkappa — APPROVED** [review]
Thanks for contributing @jackton1! Sorry for the delay, merging.

**Pull request merged**
