### PR TITLE
Make the provider compatible with Terraform v0.12

### PR DESCRIPTION
**Pull request by alexkappa**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Changes proposed in this pull request:

* Upgrade terraform to v0.12.0-rc1
* Fix acceptance tests to conform with terraform v0.12.0-rc1
* Fix examples to conform with terraform v0.12.0-rc1
* Revert encryption of `gogetcookie.sh` to allow builds from PRs

### CODE REVIEW

**Comment by dancrumb** [comment]
Is there a timeline for this?

**Comment by etiennetremel** [comment]
Hi @alexkappa, can we help somehow to have this PR merged?

**Comment by alexkappa** [comment]
Hi @dancrumb, @etiennetremel, I will spend some time this week to test a little more thoroughly and merge it. Thank you for your patience, I have my work cut out for me this weekend :)

**Comment by etiennetremel** [comment]
Thank you @alexkappa for the quick action, really appreciated.

**Comment by alexkappa** [comment]
No problem at all!

**Pull request merged**
